services:
  borg-server:
    build: .
    container_name: borg_test_serv
    ports:
      - "2222:22"
    volumes:
      - repos:/srv/repos
      - home:/home
      - srv_etc:/etc


volumes:
  repos:
  home:
  srv_etc: