services:
  borg-server:
    build: "./alpine docker"
    container_name: borg_server
    ports:
      - "2222:22"
    volumes:
      - SAVE_FOLDER:/var/backups/borg
    restart: unless-stopped
    networks:
      - backup_net

  db:
    image: mariadb:12.2-rc
    container_name: database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - backend_net

  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - SAVE_FOLDER:/var/backups/borg
    ports: 
      - "80:80"
    networks:
      - backend_net


  web:
    image: nginx:1.25-alpine
    container_name: web_server
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend_net

volumes:
  db_data: 
  SAVE_FOLDER:

networks:
  backend_net:
    driver: bridge
  backup_net:
    driver: bridge