name: strongholder
services:
  borg:
    build: 
      context: .
      dockerfile: borg/Dockerfile
    container_name: strongholder-borg
    ports:
      - "2222:22"
    volumes:
      - $VOLUMES_PATH/srv_repot:/srv
      - $VOLUMES_PATH/srv_etc:/etc
      - $VOLUMES_PATH/srv_home:/home
      - ./credentials/borg/id_ed25519.pub:/root/.ssh/id_ed25519.pub
      - $VOLUMES_PATH/tunnel_locks:/var/lib/tunnel
    restart: unless-stopped
    networks:
      - backup_net

  db:
    image: mariadb:12.2-noble
    container_name: strongholder-database
    restart: always
    env_file: credentials/db/.env
    volumes:
      - $VOLUMES_PATH/db_data:/var/lib/mysql 
      - ./mariadb:/docker-entrypoint-initdb.d
    networks:
      - database_net

  api:
    build: api
    container_name: strongholder-api
    restart: always
    env_file: credentials/api/.env
    depends_on:
      - db
    volumes:
      - ./credentials/api/id_ed25519:/home/api/.ssh/id_ed25519
    networks:
      - backup_net
      - backend_net
      - database_net


  web:
    image: nginx:1.25-alpine
    container_name: strongholder-web_server
    ports:
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./credentials/nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./credentials/nginx/privatekey.pem:/etc/nginx/certs/privatekey.pem
      - /var/log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./../web:/etc/nginx/html
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge
  backup_net:
    driver: bridge
  database_net:
    driver: bridge