name: strongholder
services:
  borg-server:
    build: ./borg
    container_name: strongholder-borg
    ports:
      - "2222:22"
    volumes:
      - srv_repot:/srv
      - ./passwd:/etc/passwd
      - ./shadow:/etc/shadow
      - ./group:/etc/group
      - ./gshadow:/etc/gshadow
      - srv_home:/home
      - ./key.pass:/etc/backup_secrets/key.pass
      - backup_server_key:/etc/backup_server_keys/
    restart: unless-stopped
    networks:
      - backup_net

  db:
    image: mariadb:12.2-rc
    container_name: strongholder-database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql 
      - ./mariadb:/docker-entrypoint-initdb.d
    networks:
      - backend_net

  api:
    build: 
      context: ..
      dockerfile: backend/strongholer/Dockerfile
    container_name: strongholder-api
    restart: always
    environment:
      DB_HOST: ${MARIADB_HOST}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_PORT: ${MARIADB_PORT}
      DB: ${MARIADB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - srv_repot:/srv
      - ./passwd:/etc/passwd
      - ./shadow:/etc/shadow
      - ./group:/etc/group
      - ./gshadow:/etc/gshadow
      - srv_home:/home
      - ./key.pass:/etc/backup_secrets/key.pass
      - backup_server_key:/etc/backup_server_keys/
    networks:
      - backend_net


  web:
    image: nginx:1.25-alpine
    container_name: strongholder-web_server
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./nginx/certs/privatekey.pem:/etc/nginx/certs/privatekey.pem
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend_net

volumes:
  db_data: 
  srv_repot:
  srv_passwd:
  srv_shadow:
  srv_group:
  srv_gshadow:
  srv_home:
  backup_server_key:

networks:
  backend_net:
    driver: bridge
  backup_net:
    driver: bridge